import "@/app/globals.css";
import { SidebarComponent } from "@/components/sidebar/SidebarComponent";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <aside className="h-screen fixed">
          <SidebarComponent />
        </aside>
        <main className="">{children}</main>
      </body>
    </html>
  );
}
